[package]
name = "aws-timestream"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-timestreamwrite = "1.12.0"
tokio = { version = "1.35.1", features = ["full"] }
